# Generated by Django 6.0 on 2025-12-15 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0003_alter_userfollows_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userblocks',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='userblocks',
            constraint=models.UniqueConstraint(fields=('user', 'blocked_user'), name='unique_user_block'),
        ),
    ]
